### PR TITLE
(Temp) function that provides analytics plugin with the bearer token.

### PR DESCRIPTION
**Pull request by sramamoorthy73**
@theganyo, @alexkhimich  Can you please code review this?

### CODE REVIEW

**Comment by theganyo** [comment]
Why not just use the config as a global place to keep this value as we do for instance ID? Directly depending upon another plugin is somewhat troubling.

**Comment by alexkhimich** [comment]
Good idea.

**Comment by sramamoorthy73** [comment]
plugin <--> plugin communication like this was a big no-no. That is why I had commented with the task item in it, and aptly marked as temp hack.
We can use the config, but even then it is still a hack. A separate plugin is anyways needed as a permanent solution.

**Comment by theganyo** [comment]
Well, that's not actually true. There is a mechanism for communication between plugins: that's the event model that apid provides.

**Comment by alexkhimich** [comment]
I think i agree with @sramamoorthy73 . For now lets go with this workaround.

**Comment by alexkhimich** [comment]
@theganyo lets accept and we need to rework this token sharing anyway, probably even the whole apigee cloud API communication layer will be generalized.

**Comment by sramamoorthy73** [comment]
I was also referring to passing values (bearer token in this case) between plugins via non-event mechanism - a quick hack. I had chat on this with @ak a while back. 
But, your config option is better, as that pattern is already established, till we have dedicated plugin. I will resend for review.

**Comment by theganyo** [comment]
Indeed, it should be.

**Pull request merged**
