### PR TITLE
detect apid_cluster_id change in config file and boot clean

### PR DESCRIPTION
**Pull request by f1erro**

### CODE REVIEW

**Comment by theganyo** [comment]
Hmm. I wonder if this should happen completely transparently like this... or if it should fail and require starting with --clean? Under what circumstance(s) would this happen and what would be the expectation of the user for that/those case(s)?

**Comment by f1erro** [comment]
Not sure, maybe they have chef/ansible deploy new `apid_config.yaml`s to a set of hosts but forget to remove existing dbs. 

should `apid_config.yaml` be considered the source of truth?

**Comment by theganyo** [comment]
Ok. So what I'm asking is: In that case would it not make sense to make it explicit? I mean, if there's a mistake that's made... do we know that's what the mistake is and what should happen? Or are we assuming more than we should be?

**Comment by alexkhimich** [comment]
If there is a stale db from previous run. When i run ./apid it should always trust apid_config.yaml file(user input). 
I should not be asked to run ./apid -clean .

**Comment by theganyo** [comment]
Ok then.

**Pull request merged**
